version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - "./api/collections:/app/collections"

  front:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VITE_API_URL: /api
    ports:
      - "80:80"
      - "443:443"
