version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - "./collections:/app/collections"

  front:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VITE_API_URL: /api
    ports:
      - "443:443"
