server {
    listen 443 ssl;
    server_name localhost; # replace with your domain or subdomain

    ssl_certificate /etc/nginx/cert.crt;
    ssl_certificate_key /etc/nginx/cert.key;
    client_max_body_size 32M;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        rewrite ^/api(.*)$ $1 break;
        proxy_pass http://api:3000;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
